version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: genai-api
    ports:
      - "8000:8000"
    env_file:
      - .env.template
    volumes:
      - ./src:/app/src
      - ./src/app/logs:/app/logs
      - ./config:/app/config
      - ./alembic:/app/alembic
    depends_on:
      - redis
    networks:
      - genai_net
    restart: unless-stopped

  redis:
    image: redis:7.2
    container_name: redis-cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - genai_net
    restart: unless-stopped

volumes:
  redis_data:

networks:
  genai_net:
    driver: bridge
